#!/usr/bin/env bash
# This is a bash script that fix my web server that is not listen on port 80
# This command copy and paste from sites-available to sites-enabled using a symbolic link
# symolic link -s
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
