#!/usr/bin/env bash
# A Program that install UFW Firwall and configure it
# to block all incoming and outgoing traffic on all ports
# except for port 22, 80 and 443

sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo systemctl stop ufw
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
